require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - gemfiles/**/*
    - vendor/bundle/**/*
  TargetRubyVersion: 2.5

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

RSpec/ExpectInHook:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Metrics/MethodLength:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - spec/**/*.rb
